FROM alpine:latest

RUN apk add cmd:pip3 --no-cache python3-dev \
    && pip3 install --upgrade pip

WORKDIR /hello
COPY . /hello
RUN pip3 --no-cache-dir install -r requirements.txt
EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["hello.py"]
